version: 0.1

phases:
  install:
    command:
    - echo Instaling Node 21 e npm...
    - curl -fsSL https://deb.nodesource.com/setup_21.x | bash -
    - apt-get install -y nodejs
  build:
    commands:
    - REACT_APP_API_URL=http://34.239.240.133 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
    - echo Rodando tests uniting...
    - npm test
  