version: 0.2

phases:
  install:
    commands:
      - echo "Atualizando repositórios..."
      - yum clean all
      - yum makecache
      - echo "Verificando se curl está instalado..."
      - if ! command -v curl &>/dev/null; then
          echo "Instalando curl...";
          yum install -y curl;
        else
          echo "curl já está instalado.";
        fi
      - echo "Instalando Node.js 20 e npm..."
      - curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      - yum install -y nodejs
      - echo "Versões instaladas:"
      - node -v
      - npm -v

  build:
    commands:
      - echo "Instalando dependências no cliente..."
      - npm install --prefix client
      - echo "Tentando executar o build do React..."
      - REACT_APP_API_URL=http://34.239.240.133 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client || true
      - echo "Executando testes unitários..."
      - npm test --prefix client

artifacts:
  files:
    - 'client/build/**/*'
    - '!client/node_modules/**/*'
