version: 0.2

phases:
  install:
    commands:
      - echo "Atualizando repositórios e verificando pacotes..."
      - yum clean all
      - yum makecache fast
      - echo "Verificando se curl já está instalado..."
      - if ! command -v curl &>/dev/null; then
          echo "curl não encontrado. Instalando...";
          yum install -y curl;
        else
          echo "curl já está instalado.";
        fi
      - echo "Instalando Node.js 20 e npm..."
      - curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
      - yum install -y nodejs
      - echo "Versões instaladas:"
      - node -v
      - npm -v

  build:
    commands:
      - echo "Configurando variáveis de ambiente e construindo o projeto React..."
      - REACT_APP_API_URL=http://34.239.240.133 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo "Executando testes unitários..."
      - npm test

artifacts:
  files:
    - 'build/**/*'
    - '!node_modules/**/*'
