version: 0.2

phases:
  install:
    commands:
      - apt-get update -y
      - apt-get upgrade -y
      - echo "Instalando Node.js 18 e npm..."
      - curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      - sudo yum install -y nodejs
  
  build:
    commands:
      - npm install --loglevel=error
      - echo "Configurando e construindo o projeto React..."
      - REACT_APP_API_URL=http://34.239.240.133 SKIP_PREFLIGHT_CHECK=true npm run build --prefix client
      - echo "Executando testes unitários..."
      - npm test
