version: '3'
services:
  database:
      image: postgres:10.17
      environment:
        - "POSTGRES_USER=postgres"
        - "POSTGRES_PASSWORD=postgres"
        - "POSTGRES_DB=bia"
      ports:
        - 5433:5432